export const GOOGLE_FIT_AUTHORIZATION_SUCCESS = 'GOOGLE_FIT_AUTHORIZATION_SUCCESS'
export const GOOGLE_FIT_AUTHORIZATION_FAILURE = 'GOOGLE_FIT_AUTHORIZATION_FAILURE'

export const DAILY_STEP_COUNT_REQUEST = 'DAILY_STEP_COUNT_REQUEST'
export const DAILY_STEP_COUNT_SUCCESS = 'DAILY_STEP_COUNT_SUCCESS'
export const DAILY_STEP_COUNT_FAILURE = 'DAILY_STEP_COUNT_FAILURE'

export const FETCH_ACTIVITIES_REQUEST = 'FETCH_ACTIVITIES_REQUEST'
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS'
export const FETCH_ACTIVITIES_FAILURE = 'FETCH_ACTIVITIES_FAILURE'